<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPUAKYIW2749" name="talab.TestAdditionalOperations" tests="21" failures="0" timestamp="3 Nov 2016 10:29:39 GMT" time="0.004" errors="2">
  <testcase name="testIsNegativeTrue" time="0.002" classname="talab.TestAdditionalOperations"/>
  <testcase name="testSqrt" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testIsNegativeTrue" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testIsNegativeFalse" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testPow" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testPow" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testPow" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testIsNegativeFalse" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testIsPositiveTrue" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testIsPositiveFalse" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testIsPositiveFalse" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testIsPositiveTrue" time="0.001" classname="talab.TestAdditionalOperations"/>
  <testcase name="testIsPositiveTrue" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testIsNegativeTrue" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testIsNegativeTrue" time="0.000" classname="talab.TestAdditionalOperations">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at talab.TestAdditionalOperations.testIsNegativeTrue(TestAdditionalOperations.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testIsNegativeTrue -->
  <testcase name="testPow" time="0.000" classname="talab.TestAdditionalOperations">
    <error type="java.lang.AssertionError" message="expected [0.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [0.0] but found [1.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at talab.TestAdditionalOperations.testPow(TestAdditionalOperations.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testPow -->
  <testcase name="testIsPositiveFalse" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testIsNegativeFalse" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testPow" time="0.000" classname="talab.TestAdditionalOperations"/>
  <testcase name="testSqrt" time="0.001" classname="talab.TestAdditionalOperations"/>
  <testcase name="testIsPositiveFalse" time="0.000" classname="talab.TestAdditionalOperations"/>
</testsuite> <!-- talab.TestAdditionalOperations -->
